"""PBIP emitter — a complete Power BI project, not a measures file to assemble.

Produces a semantic model (TMDL) plus a laid-out three-page report (PBIR), so the
output opens in Power BI Desktop as a finished dashboard rather than a blank canvas.

**What this cannot do, stated plainly:** `.pbix` is a compiled binary produced only
by Power BI Desktop, which is Windows-only. There is no supported cross-platform
PBIP -> PBIX compiler. This emits PBIP *source*; converting it is a manual Save As.
Nothing in the output claims otherwise, and a test enforces that.
"""
from __future__ import annotations

import json
import uuid
from pathlib import Path

from atlas.exporters.dax import DaxMeasure
from atlas.exporters.dax_measures import build_measures, stakeholder_measures
from atlas.exporters.pbip import layout as _layout
from atlas.exporters.pbip.pbir import (
    dumps, render_page, render_pages_metadata, render_report, render_visual,
)
from atlas.exporters.pbip.schemas import (
    PBIP_SCHEMA, PBIP_VERSION, PBIR_DEFINITION_VERSION, PBIR_SCHEMA, PBIR_VERSION,
    PBISM_SCHEMA, PBISM_VERSION, PLATFORM_SCHEMA, VERSION_SCHEMA,
)
from atlas.exporters.pbip.tmdl import (
    TmdlColumn, TmdlTable, m_csv_partition, render_database, render_model,
    render_relationships, render_table,
)
from atlas.lib.binning import edges_to_dax_switch
from atlas.lib.export_registry import ExportContext, Exporter, register_exporter
from atlas.lib.risk_tiers import load_policy

__all__ = ["PbipExporter"]

SCORES_TABLE = "RiskScores"


def _platform(display_name: str, item_type: str) -> str:
    return dumps({
        "$schema": PLATFORM_SCHEMA,
        "metadata": {"type": item_type, "displayName": display_name},
        "config": {"version": "2.0",
                   "logicalId": str(uuid.uuid5(uuid.NAMESPACE_OID,
                                               f"{item_type}:{display_name}"))},
    })


@register_exporter
class PbipExporter(Exporter):
    id = "pbip"
    description = ("Complete Power BI project (PBIP): TMDL semantic model + a "
                   "laid-out PBIR report.")
    requires = ("binding",)

    def emit(self, ctx: ExportContext) -> list[str]:
        from atlas.playbooks.binding import ColumnRole

        b = ctx.binding
        target = b.one(ColumnRole.TARGET)
        entity = b.one(ColumnRole.ENTITY)
        if not target or not entity:
            from atlas.lib.export_registry import ExportUnavailable
            raise ExportUnavailable(
                "the Power BI project needs a bound target and entity column; this "
                "run bound target=%r entity=%r" % (target, entity))

        table = str(ctx.options.get("dax_table") or b.table or "Data").split(".")[-1]
        name = ctx.options.get("pbip_name") or "AtlasReport"
        root = Path("powerbi")
        sm = root / f"{name}.SemanticModel"
        rp = root / f"{name}.Report"
        written: list[str] = []

        def w(rel: Path, text: str) -> None:
            written.append(ctx.write(str(rel), text))

        plan = getattr(ctx.result, "feature_plan", None)
        policy = load_policy(getattr(plan, "tier_policy_profile", "default"))
        measures = self._measures(ctx, table, target, entity, plan)
        has_scores = (ctx.run_dir / "risk_scores.csv").exists()

        # ---------------- project descriptor ----------------
        w(root / f"{name}.pbip", dumps({
            "$schema": PBIP_SCHEMA, "version": PBIP_VERSION,
            "artifacts": [{"report": {"path": f"{name}.Report"}}],
            "settings": {"enableAutoRecovery": True},
        }))

        # ---------------- semantic model ----------------
        w(sm / ".platform", _platform(name, "SemanticModel"))
        w(sm / "definition.pbism", dumps({
            "$schema": PBISM_SCHEMA, "version": PBISM_VERSION,
            "settings": {"qnaEnabled": True},
        }))

        fact = self._fact_table(ctx, table, target, plan)
        tables = [fact]
        rels: list[tuple[str, str, str, str]] = []
        if has_scores:
            tables.append(self._scores_table(ctx, entity, policy))
            # 1:1 on the entity id, modelled explicitly rather than merged in Power
            # Query, so risk_scores.csv stays independently refreshable.
            rels.append((table, entity, SCORES_TABLE, entity))

        # Measures live on a dedicated table so they are not buried among columns.
        measures_table = TmdlTable(
            name="_Measures", measures=measures,
            description="Generated by Atlas. Compiled from metrics.yaml and the "
                        "column bindings this analysis actually used.",
            columns=[TmdlColumn(name="_", dtype="INTEGER", is_hidden=True)],
            partition_m='let\n    Source = #table({"_"}, {{1}})\nin\n    Source')
        tables.append(measures_table)

        w(sm / "definition" / "database.tmdl", render_database(name))
        w(sm / "definition" / "model.tmdl", render_model(
            [t.name for t in tables],
            annotations={"AtlasTierPolicyDigest": f'"{policy.digest()}"'}))
        if rels:
            w(sm / "definition" / "relationships.tmdl", render_relationships(rels))
        for t in tables:
            w(sm / "definition" / "tables" / f"{t.name}.tmdl", render_table(t))

        # ---------------- report ----------------
        w(rp / ".platform", _platform(name, "Report"))
        w(rp / "definition.pbir", dumps({
            "$schema": PBIR_SCHEMA, "version": PBIR_DEFINITION_VERSION,
            "datasetReference": {"byPath": {"path": f"../{name}.SemanticModel"}},
        }))
        d = rp / "definition"
        w(d / "version.json", dumps({"$schema": VERSION_SCHEMA,
                                     "version": PBIR_VERSION}))
        w(d / "report.json", dumps(render_report(
            annotations={"AtlasTierPolicyDigest": policy.digest()})))

        pages = _layout.build_pages(
            table=table, scores_table=SCORES_TABLE, entity=entity,
            measure_names=[m.name for m in measures], plan=plan,
            has_scores=has_scores)
        w(d / "pages" / "pages.json", dumps(render_pages_metadata(pages)))
        for p in pages:
            w(d / "pages" / p.name / "page.json", dumps(render_page(p)))
            for i, v in enumerate(p.visuals):
                vname = v.resolved_name(p.name, i)
                w(d / "pages" / p.name / "visuals" / vname / "visual.json",
                  dumps(render_visual(v, page=p.name, index=i)))

        # ---------------- docs ----------------
        w(root / "LAYOUT_GUIDE.md",
          _layout.render_guide(name, pages, measures, policy, table, has_scores))
        w(root / "PBIP_LIMITATIONS.md", _limitations(name))
        return written

    # ------------------------------------------------------------------
    def _measures(self, ctx, table, target, entity, plan) -> list[DaxMeasure]:
        cols = None
        con = getattr(ctx, "con", None)
        if con is not None:
            try:
                from atlas.connectors.base import TableRef
                cols = {c.name for c in con.get_schema(TableRef(table)).columns}
            except Exception:
                cols = None
        compiled, _ = build_measures(table, available_columns=cols)
        numeric = list(getattr(plan, "numeric", []) or [])
        value_col = next((c for c in numeric
                          if any(k in c.lower() for k in
                                 ("spend", "revenue", "value", "amount", "arr", "mrr"))),
                         None)
        return compiled + stakeholder_measures(
            table, target=target, entity=entity, numeric=numeric,
            value_column=value_col, tier_table=SCORES_TABLE)

    def _fact_table(self, ctx, table, target, plan) -> TmdlTable:
        cols: list[TmdlColumn] = []
        con = getattr(ctx, "con", None)
        if con is not None:
            try:
                from atlas.connectors.base import TableRef
                for c in con.get_schema(TableRef(table)).columns:
                    cols.append(TmdlColumn(name=c.name, dtype=c.dtype))
            except Exception:
                pass
        source = ctx.options.get("source_path") or f"{table}.csv"

        calc: list[tuple[str, str, str]] = []
        for spec in list(getattr(plan, "binnings", []) or []):
            # Only emitted when the descriptive stage MEASURED a threshold effect —
            # the bucket column is a finding, not decoration.
            calc.append((
                f"{spec.column} Bucket",
                edges_to_dax_switch(f"'{table}'[{spec.column}]", spec.edges, spec.labels),
                f"Bands from a measured threshold effect: {spec.reason}"))
        return TmdlTable(
            name=table, columns=cols, partition_m=m_csv_partition(source, columns=cols),
            calculated_columns=calc,
            description=f"Source table for the analysis. Target column: {target}.")

    def _scores_table(self, ctx, entity, policy) -> TmdlTable:
        cols = [
            TmdlColumn(name=entity, dtype="BIGINT"),
            TmdlColumn(name=policy.score_field, dtype="DOUBLE",
                       format_string='"0.000"'),
            TmdlColumn(name="risk_tier", dtype="VARCHAR"),
            TmdlColumn(name="flagged", dtype="BIGINT"),
            TmdlColumn(name="split", dtype="VARCHAR", is_hidden=True),
            TmdlColumn(name="actual", dtype="BIGINT", is_hidden=True),
            TmdlColumn(name="top_factor_1", dtype="VARCHAR"),
            TmdlColumn(name="top_factor_2", dtype="VARCHAR"),
            TmdlColumn(name="top_factor_3", dtype="VARCHAR"),
        ]
        return TmdlTable(
            name=SCORES_TABLE, columns=cols,
            partition_m=m_csv_partition("../risk_scores.csv", columns=cols),
            description=("Per-entity model scores. Tier bands come from "
                         f"risk_tiers.yaml (digest {policy.digest()}), the same "
                         "definition the CSV used."))


def _limitations(name: str) -> str:
    return f"""# What this export is, and is not

## It is PBIP project **source**

This run generated a Power BI **project** — a folder of text files (TMDL for the
semantic model, JSON for the report). That is the format Power BI Desktop reads and
writes for source control.

## It is **not** a `.pbix`

`.pbix` is a compiled binary. It is produced only by Power BI Desktop, which runs on
Windows, and there is no supported cross-platform tool that compiles PBIP into PBIX.
Atlas did not produce one and does not claim to have.

To get a single-file deliverable:

1. Open `{name}.pbip` in Power BI Desktop.
2. **File -> Save As** -> choose `.pbix`.

## Format status

PBIR (the enhanced report format used here) became the default for new reports in
January 2026, and for Power BI Desktop from the March 2026 release. General
Availability is planned for Q3 2026, so it is the current default but still formally
in preview. If your Desktop build predates March 2026, enable
**File -> Options and settings -> Options -> Preview features ->
Store reports using enhanced metadata format (PBIR)** before opening this project.

## What was verified, and what was not

Every `$schema` URL and version in this project was checked against Microsoft
documentation on 2026-07-30 (see `atlas/exporters/pbip/schemas.py`, which records the
confidence level of each). Two things are marked **assumed** there rather than
verified: the `.platform` Git-integration schema, and the `visualType` identifiers.

A wrong `.platform` is harmless — the project opens without it. A wrong `visualType`
renders an empty visual rather than failing loudly, so if a chart appears blank, that
constant is the first thing to check.

## Automated checks cannot prove this opens

The test suite verifies that every JSON parses, that schema URLs match the recorded
constants, that every measure and column a visual references actually exists in the
model, and that no placeholder survives. None of that proves Power BI Desktop will
open the file. **That requires a manual check on Windows** and is the stated exit
criterion for this feature.
"""
