"""Pandas Repair Engine: emit an equivalent pandas transformation script.

For file sources (CSV/Excel/Parquet) the same repair plan is expressible as a
pandas pipeline. Emitted as a runnable, reviewable script for the audit trail —
Atlas materialises via SQL (sql_engine) but records the pandas equivalent so the
transformation is portable and human-auditable.
"""
from __future__ import annotations


def build_pandas_script(source_path: str, base_table: str, clean_table: str,
                        transforms: list, *, dedup: bool) -> str:
    """A standalone pandas script reproducing the clean layer from the raw file."""
    lines = [
        "# Auto-generated by Atlas Data Quality Copilot — pandas equivalent of the",
        f"# semantic clean layer '{clean_table}' (raw source is never modified).",
        "import pandas as pd",
        "",
        "# Config mappings referenced by derived columns (see rules/*.yaml):",
        "from atlas.quality.rules_loader import country_region_mapping, country_standardisation",
        "COUNTRY_TO_REGION = country_region_mapping()['country_to_region']",
        "CANONICAL = country_standardisation()",
        "",
        f"df = pd.read_excel({source_path!r}) if {source_path!r}.endswith(('.xlsx', '.xls')) "
        f"else pd.read_csv({source_path!r})",
        "",
    ]
    if dedup:
        lines.append("df = df.drop_duplicates()  # duplicate_detection")
    for t in transforms:
        if t.pandas_code:
            lines.append(f"{t.pandas_code}  # {t.module_id}")
    lines += ["", f"# df is now the clean layer ({clean_table}); write out as needed.", ""]
    return "\n".join(lines)
